
#!/bin/bash
#Menu
clear
echo -e " "
echo -e "\033[01;33m  }~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~{"
echo -e "  {    Wallcom to server Debian7-8    }"
echo -e "  }~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~{"
echo -e "  { Script mod by kguza }" 
echo -e "  }~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~{"
echo -e "  {   prin { menu } Show menu items   }"
echo -e "  }~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~{"
echo -e " "
echo -e "\033[1;36m { a } adduser Create SSH & OpenVPN"
echo -e "\033[1;36m { b } test user 1day"
echo -e "\033[1;36m { c } Change Name & Passwd"
echo -e "\033[1;36m { d } 1:Change Password,2:Change device login,3:Change Exp"
echo -e "\033[1;36m { e } delete user SSH & OpenVPN"
echo -e "\033[1;36m { f } Auto delete user Expres"
echo -e "\033[1;36m { g } user view all member SSH & OpenVPN"
echo -e "\033[1;36m { h } restart service, OpenVPN and SSH"
echo -e "\033[1;36m { i } speedtest VPS"
echo -e "\033[1;36m { j } Check bandwidth total data internet"
echo -e "\033[1;36m { k } Check bandwidth to ip"
echo -e "\033[1;36m { l } about this system"
echo -e "\033[1;36m { m } ban user"
echo -e "\033[1;36m { n } unban user"
echo -e "\033[1;36m { o } Install And Update File HTTP"
echo -e "\033[1;36m { p } about script auto install"
echo -e "\033[1;36m { q } Credit to http Injector"
echo -e "\033[1;36m { r  } Setting reboot time"
echo -e "\033[1;36m { s } backup"
echo -e "\033[1;36m { reboot } reboot VPS"
echo -e "\033[1;36m { exit } close Putty/Connecbot/JuiceSSH"
echo -e " "